#!/bin/bash
# my own script for
# grabbing and encoding a single track from cd
# 1-2002 by Brian O.Noelle
# grabAndEncode <trackNr> <artist> <title> <outfile>
echo "start grabbing..."
cdparanoia -q $1 "$4.wav"
echo "..done"

echo "start encoding..."
notlame -S -h --preset studio --ta "$2" --tt "$3" "$4".wav "$4.part"
echo "..done"

rm "$4.wav"
mv "$4.part" "$4"
