#!/bin/bash
# script for grabbing and encoding a single track from cd
# example script provided for yammi (see yammi.sourceforge.net)
# 1-2002 by Oliver Noelle
# usage: grabAndEncode <trackNr> <artist> <title> <outfile>
echo "start grabbing..."
cdparanoia -q $1 "$4.wav"
echo "..done"

echo "start encoding..."
notlame -S -h --preset studio --ta "$2" --tt "$3" "$4".wav "$4.part"
echo "..done"

rm "$4.wav"
mv "$4.part" "$4"
