#undef PACKAGE
#undef VERSION
#undef HAVE_LIBSM
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef ENABLE_NLS

#undef ENABLE_OGGLIBS
#undef ENABLE_ID3LIB

#undef HAVE_ICONV_OPEN
#undef HAVE_LANGINFO_CODESET
